apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-controllers
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-config
  interval: 1h
  retryInterval: 1m
  timeout: 5m0s
  prune: true
  wait: true
  sourceRef:
    kind: OCIRepository
    name: manifests
    namespace: flux-system
  path: ./infrastructure/controllers/
