apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: rancher-stable
  namespace: cattle-system
spec:
  interval: 120m
  url: https://releases.rancher.com/server-charts/stable
