apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  releaseName: ingress-nginx
  chart:
    spec:
      chart: ingress-nginx
      version: 4.11.2
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress-nginx
  interval: 60m
  values:
    controller:
      extraArgs:
        update-status: "true"
      ingressClassResource:
        default: true
      admissionWebhooks:
        enabled: false
      autoscaling:
        enabled: false
        minReplicas: 1
        maxReplicas: 3
        targetCPUUtilizationPercentage: 50
        targetMemoryUtilizationPercentage: 85
      resources:
        requests:
          cpu: 100m
          memory: 250Mi
        limits:
          memory: 512Mi
      service:
        type: 'LoadBalancer'
        # loadBalancerClass: 'io.cilium/l2-announcer'
        #loadBalancerClass: metallb
