name: Push Flux Artifact to OCI Registry

on:
  workflow_dispatch:
    inputs:
      oci_registry:
        description: 'OCI registry to deploy'
        required: true
        default: 'oci://docker.io/lutfailham/dev-flux-gitops'
      cluster_name:
        description: 'Cluster name to deploy'
        required: false
        default: 'dev-cluster'

jobs:
  push_flux_artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@main

      - name: Push Flux artifact to OCI registry
        run: |
          flux push ${{ github.event.inputs.oci_registry }}":${{ github.event.inputs.cluster_name }}" \
            --path="./manifests/${{ github.event.inputs.cluster_name }}/" \
            --source="${{ github.repository_url }}" \
            --revision="${{ github.sha }}" \
            --annotations="org.opencontainers.image.url=${{ github.repository_url }}" \
            --annotations="org.opencontainers.image.title=${{ github.event.repository.name }}" \
            --annotations="com.github.event_id=${{ github.run_id }}" \
            --annotations="com.github.run_url=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
